# Contains settings that will be used throughout the tool
# To update this with your personal settings, please duplicate this file
# and name it 'local.settings.yml'. This way your personal tokens will be safe

# Paste your personal ETM in this field. Never push this to GitHub!
personal_etm_token: etm_eyJraWQiOiJkODI5ZTk3YTU4ZDhhOTQyYjg3NGI5ZjNiZWI3ZDJlNGY0MTA5ZjIzNWE0Y2NhMDkzYmU5MzFiMzY1NTlkNGI2IiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL215LmVuZXJneXRyYW5zaXRpb25tb2RlbC5jb20iLCJpYXQiOjE3NTY5MDM0MzksImF1ZCI6Imh0dHBzOi8vZW5naW5lLmVuZXJneXRyYW5zaXRpb25tb2RlbC5jb20gaHR0cHM6Ly8yMDI1LTAxLmVuZ2luZS5lbmVyZ3l0cmFuc2l0aW9ubW9kZWwuY29tIiwic2NvcGVzIjoib3BlbmlkIHB1YmxpYyBzY2VuYXJpb3M6cmVhZCBzY2VuYXJpb3M6d3JpdGUiLCJqdGkiOiJkM2M4NjMwNi03ZmRkLTRlZWEtYTdkMy04MmNjNjUxYjRkM2QiLCJzdWIiOjE1ODk1LCJ1c2VyIjp7ImlkIjoxNTg5NSwiZW1haWwiOiJseXMyNDQ4Mzk4MTYxQGdtYWlsLmNvbSIsIm5hbWUiOiJ5bnNobmFsaSIsImFkbWluIjpmYWxzZX0sImV4cCI6MTc1OTQ5NTQzOX0.NybF4ptIE9DRUwtibRmAFE83RP3ZzBcCuydoAtPoxytl7H7LWz4qWUCWPn-9RasIjHkkd1BitvSGgxGfW-tPJyfwCk0a1QbD7UcSLM48pPjGarIrOqk9PHgztYc8TJHCVhd8UC7s7dzf5CqQZqELoJml5TjxG7_Q6g1RYFZBBL_5tvvmRxS7HYOnhGx0LXXeSQuf0TUFof_bR59HSGx5CLAOoBT9xN-9bAGWhVmYJ4zZ9odlBnN5jQIMqKcMnqttI05J3CRuchMk1dDHNvpdyuXISdWEHF53Q03lYLi4mpXtv1fkOUYCb-UR9CBuxKmNO4-HLV7feR7qZJK7gw78bw

# Location of the input files, you can change this to be any folder on your computer
input_file_folder: data/input
input_curves_folder: data/input/curves
input_orders_folder: data/input/orders

output_file_folder: data/output
output_curves_folder: data/output/curves
output_orders_folder: data/output/orders

# Where your local model is run
local_engine_url: http://localhost:3000/api/v3
local_model_url: http://localhost:3001

# URLs of your proxy server addresses (replace the examples below by your own settings)
# Never push authenticated servers (including user name and password) to Github!
proxy_servers:
  # http: http://user:pass@proxy.sample.com:8080
  # https: http://user:pass@secureproxy.sample.com:8080

# The separator your CSV files are using. The default is ',', but many European computers
# export CSV with a ';' as separator from Excel instead.
csv_separator: ','

# The decimal separator your CSV files are using. The default is '.', but depending on the
# national conventions, comma could be used as a decimal seperator instead.
decimal_seperator: '.'
